services:
  - type: web
    name: doctor-appointment-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    plan: free
    envVars:
      - key: PORT
        value: 5000
